### ISSUE TITLE
Provide written recommendations for making access to HDF5 files more performant

### ISSUE THREAD

**Issue by asteiker** [ICESAT-2HackWeek/h5cloud#21]
Based on our benchmarking results, we ought to provide written guidance and recommedations on how to make our existing HDF5 files more performant. E.g.:

- What can the NSIDC DAAC provide in terms of repacking upon ingest to Earthdata Cloud
- What can we recommend or support in terms of the utilization of h5coro for end-users 
- What can we recommend in terms of the data file production that the SIPS is responsible for in terms of re-packing. 
- etc.

```[tasklist]
### Tasks
- [ ] Content creation: Problem statement
- [ ] Content creation: Cloud Optimized Geospatial Formats
- [ ] Content creation: Access Tools
- [ ] Content creation: Methodology
- [ ] Content creation: Results
- [ ] Content Creation: HDF5 Performance Recommendations for ICESat‐2 ATL03
```

**Comment by asteiker** [comment]
See https://github.com/ICESAT-2HackWeek/h5cloud/wiki/Cloud-Optimized-Format-Investigation-for-ICESat%E2%80%902:-Study-Results-and-Recommendations
