### ISSUE TITLE
Re-plot performance testing based on individual files

### ISSUE THREAD

**Issue by asteiker** [ICESAT-2HackWeek/h5cloud#25]
The plot shown in #19 demonstrates collated testing runs across i/o libraries for each data format (original, repack, kerchunk-original, kerchunk-repack). It would be more valuable to create a scatter plot of the performance testing for individual file runs based on #20  to better observe the within-group variability. Grouping by tool may be most valuable.
```[tasklist]
### Tasks
- [x] Update h5cloud/helpers/s3filelinks.json to point to persistent data with new bucket
- [x] Re-run /h5cloud/notebooks/run-tests.ipynb with a  new results directory
- [x] Persist pandas dataframe in benchmark notebook to write to csv
- [x] Replot as scatter plot grouped by tool
- [x] Plot all file and i/o param combinations on a single plot
```

**Comment by asteiker** [comment]
Dependent on #28
