### ISSUE TITLE
Produce re-chunked data based on ICESat-2 data production script

### ISSUE THREAD

**Issue by asteiker** [ICESAT-2HackWeek/h5cloud#34]
```[tasklist]
### Tasks
- [x] Generate re-chunked ATL03 test file: Page Agg + 100K chunk size
- [x] Investigate file size increase when using paged agg + rechunked
- [x] Generate re-chunked ATL03 test file: Multiple file sizes
```

**Comment by asteiker** [comment]
See [https://github.com/ICESat2-SlideRule/sliderule/blob/main/clients/python/utils/i2_optimize.py](https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FICESat2-SlideRule%2Fsliderule%2Fblob%2Fmain%2Fclients%2Fpython%2Futils%2Fi2_optimize.py&data=05%7C02%7Camy.steiker%40Colorado.EDU%7C26b7437200874c424a3608dc5f9e1429%7C3ded8b1b070d462982e4c0b019f46057%7C1%7C0%7C638490379769724326%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=6VBf5wcg2gTIa8vVfeo%2BX9qjf5Fg99x%2BAbhMnr7K5F8%3D&reserved=0)  to leverage for the generation of the re-chunked files.

**Comment by betolink** [comment]
I generated a new batch of cloud-optimized ATL03 files to test. I also opened a discussion on SlideRule https://github.com/orgs/SlideRuleEarth/discussions/398 to start testing them on their side. Next I'll be generating our kerchunk files again and running the benchmarks one more time.
