### ISSUE TITLE
Produce initial recommendation on the best combination of page aggregation or user block strategy + rechunking parameters for ATL03

### ISSUE THREAD

**Issue by asteiker** [ICESAT-2HackWeek/h5cloud#35]
```[tasklist]
### Tasks
- [x] Run benchmark tests for ATL03 test files - all combinations of chunk + strategy
- [x] Plot results of chunk + strategy combinations
- [x] Report recommendation on chunk + strategy parameters to ICESat-2 Data Production Team
```

**Comment by asteiker** [comment]
- User block was determined to be problematic because it's not directly available in the H5 library, and it can vary based on individual granule. This was also problematic for the ICESat-2 production code. This could be worth revisiting in the future / with the next upcoming version release.
- Focus instead of page aggregation + rechunking: 8MB page size and 100k photons per chunk.
